export const attaccanti: string[] = [
    "Malen (ROM)",
    "Martinez L. (INT)",
    "Hojlund (NAP)",
    "Thuram (INT)",
    "Ramos G. (MIL)",
    "Douvikas (COM)",
    "Kean (COM)",
    "Kolo Muani (JUV)",
    "Woltemade (JUV)",
    "Scamacca (ATA)",
    "Davis K. (UDI)",
    "Berardi (SAS)",
    "Esposito F.P. (INT)",
    "Yildiz (JUV)",
    "Dybala (ROM)",
    "Krstovic (ATA)",
    "De Ketelaere (ATA)",
    "Laurientè (SAS)",
    "Simeone (TOR)",
    "Raspadori (ATA)",
    "Castro S. (ROM)",
    "Santos A. (NAP)",
    "Pinamonti (LAZ)",
    "Dovbyk (BOL)",
    "Colombo (GEN)",
    "Diao (COM)",
    "Beto (FIO)",
    "Soulè (ROM)",
    "Varela G. (MON)",
    "Pellegrino M. (FIO)",
    "Esposito Se. (SAS)",
    "Romero D. (PAR)",
    "Kevin Carlos (CAG)",
    "Tourè E. (PAR)",
    "Adams A. (VEN)",
    "Bowie (SAS)",
    "Adams C. (TOR)",
    "Bobcek (FRO)",
    "Osmajic (GEN)",
    "Piccoli (BOL)",
    "Yeboah J. (VEN)",
    "Raimondo (FRO)",
    "Boga (JUV)",
    "Gnonto (FIO)",
    "Kvernadze (FRO)",
    "Ghedjemis (FRO)",
    "Geubbels (LEC)",
    "Cutrone (MON)",
    "Neres (NAP)",
    "Camarda (MIL)",
    "Maldini (CAG)",
    "Zeballos (MON)",
    "Bonny (INT)",
    "Fatah (LEC)",
    "Rrahmani Al. (VEN)",
    "Lang (NAP)",
    "Vitinha O. (GEN)",
    "Ngonge (MON)",
    "Birligea (FRO)",
    "Lontani (PAR)",
    "Mendy P. (CAG)",
    "Elphege (PAR)",
    "Stulic (LEC)",
    "N'Dri (LEC)",
    "Lucca (NAP)",
    "Zapata D. (TOR)",
    "Kulenovic (TOR)",
    "Ekhator (JUV)",
    "Borrelli (CAG)",
    "Nzola (CAG)",
    "Milik (JUV)",
    "Gueye (UDI)",
    "Giovane (NAP)",
    "Noslin (LAZ)",
    "Sulemana K. (ATA)",
    "Mota (MON)",
    "Adorante (VEN)",
    "Robinson J. (MON)",
    "Havel (GEN)",
    "Frigan (PAR)",
    "Enem (BOL)",
    "Robinho Junior (GEN)",
    "Bayo V. (UDI)",
    "De Martis (PAR)",
    "Lauberbach (VEN)",
    "Lisman (VEN)",
    "Trepy (CAG)"
];