export const calciatori: string[] = [
  "Svilar (ROM)",
  "Vicario (JUV)",
  "Martinez Jo. (INT)",
  "Carnesecchi (ATA)",
  "Maignan (MIL)",
  "Butez (COM)",
  "Meret (NAP)",
  "De Gea (FIO)",
  "Mandas (LAZ)",
  "Skorupski (BOL)",
  "Caprile (CAG)",
  "Okoye (UDI)",
  "Perri (TOR)",
  "Falcone (LEC)",
  "Sanchez Ro. (COM)",
  "Bijlow (GEN)",
  "Muric (SAS)",
  "Stankovic F. (VEN)",
  "Daffara (PAR)",
  "Palmisani (FRO)",
  "Milinkovic-Savic (NAP)",
  "Thiam (MON)",
  "Corvi (PAR)",
  "Provedel (INT)",
  "Desplanches (FRO)",
  "Tornqvist (MON)",
  "Mascardi (TOR)",
  "Mrozek (UDI)",
  "Grabara (JUV)",
  "Pisseri (FRO)",
  "Penev (LEC)",
  "Renzetti (LAZ)",
  "Happonen (BOL)",
  "Pozzi (VEN)",
  "Strajnar (MON)",
  "Lolic (FRO)",
  "Siviero (TOR)",
  "Motta (LAZ)",
  "Pessina Mas. (BOL)",
  "De Marzi (ROM)",
  "Torriani (MIL)",
  "Sherri (CAG)",
  "Stolz (GEN)",
  "Christensen O. (FIO)",
  "Paleari (TOR)",
  "Montipò (VEN)",
  "Turati (SAS)",
  "Russo A. (SAS)",
  "Ghidotti (PAR)",
  "Contini (NAP)",
  "Terracciano (MIL)",
  "Vigorito (COM)",
  "Satalino (SAS)",
  "Pinsoglio (JUV)",
  "Di Gennaro (INT)",
  "Gollini (ROM)",
  "Padelli (UDI)",
  "Sommariva (GEN)",
  "Lezzerini (FIO)",
  "Sportiello (ATA)",
  "Radunovic (CAG)",
  "Dimarco (INT)",
  "Wesley (ROM)",
  "Molina N. (ROM)",
  "Mancini (ROM)",
  "Rrahmani (NAP)",
  "Akanji (INT)",
  "Pavlovic (MIL)",
  "Kalulu (JUV)",
  "Bastoni (INT)",
  "Solet (UDI)",
  "N'Dicka (ROM)",
  "Gila (MIL)",
  "Di Lorenzo (NAP)",
  "Bisseck (INT)",
  "Stones (INT)",
  "Ostigard (GEN)",
  "Spence (INT)",
  "Hermoso (ROM)",
  "Chalobah T. (COM)",
  "Ramon (COM)",
  "Scalvini (ATA)",
  "Vasquez (GEN)",
  "Dodò (FIO)",
  "Vojvoda (UDI)",
  "Kamara H. (UDI)",
  "Couto (COM)",
  "Spinazzola (NAP)",
  "Bartesaghi (MIL)",
  "Valeri (PAR)",
  "Miranda J. (BOL)",
  "Tiago Gabriel (LEC)",
  "Delprato (PAR)",
  "Theate (BOL)",
  "Zappacosta (ATA)",
  "Cambiaso (JUV)",
  "Koulierakis (ROM)",
  "Doekhi (LAZ)",
  "Celik (JUV)",
  "Comuzzo (TOR)",
  "Tavares N. (LAZ)",
  "Belghali (TOR)",
  "Dragusin (FIO)",
  "Mina (CAG)",
  "Sutalo J. (LAZ)",
  "Idzes (SAS)",
  "Zortea (BOL)",
  "Jimenez A. (FIO)",
  "Lucumì (JUV)",
  "Badiashile (NAP)",
  "Mangas (MON)",
  "Bracaglia (FRO)",
  "Obert (CAG)",
  "Gabbia (MIL)",
  "Coco (TOR)",
  "Ismajli (TOR)",
  "Hien (ATA)",
  "Valle (COM)",
  "Kristensen T. (ATA)",
  "Carlos Augusto (INT)",
  "Marusic (LAZ)",
  "Romagnoli (LAZ)",
  "Bernasconi (ATA)",
  "Bellanova (ATA)",
  "Sugawara (CAG)",
  "Heggem (BOL)",
  "Caleta-Car (SAS)",
  "Buongiorno (NAP)",
  "Kaiki (COM)",
  "Obrador (SAS)",
  "Marcandalli (GEN)",
  "Holm (BOL)",
  "Monterisi (FRO)",
  "Pedraza (LAZ)",
  "Pavard (INT)",
  "Leysen F. (SAS)",
  "Viery (FIO)",
  "Fortini (TOR)",
  "Veiga D. (LEC)",
  "Beukema (NAP)",
  "Balerdi (ROM)",
  "Gallo (LEC)",
  "Oyono A. (FRO)",
  "Tomori (MIL)",
  "Kolasinac (ATA)",
  "De Winter (MIL)",
  "Valdepenas (FIO)",
  "Calvani (FRO)",
  "Zè Pedro (CAG)",
  "Bella-Kotchap (VEN)",
  "Kempf (COM)",
  "Olivera (NAP)",
  "Kelly L. (JUV)",
  "Gaspar K. (LEC)",
  "Patterson (TOR)",
  "Correia T. (VEN)",
  "Ghilardi (ROM)",
  "Doig (SAS)",
  "Haps (VEN)",
  "Kofler (CAG)",
  "Rodriguez Ju. (CAG)",
  "Provstgaard (LAZ)",
  "Rensch (ROM)",
  "Favasuli (NAP)",
  "Comert (TOR)",
  "Siebert (LEC)",
  "Hainaut (VEN)",
  "Birindelli (MON)",
  "Kossounou (ATA)",
  "Kabasele (UDI)",
  "Mitaj (GEN)",
  "Mussolini (LAZ)",
  "Vitik (BOL)",
  "Smolcic I. (COM)",
  "Gatti (JUV)",
  "Bertola (UDI)",
  "Zanoli (UDI)",
  "Parisi (FIO)",
  "Valenti (PAR)",
  "Walukiewicz (SAS)",
  "Juan Jesus (VEN)",
  "Arizala (UDI)",
  "Cittadini (FRO)",
  "Pongracic (FIO)",
  "Terzic (FRO)",
  "Moreno M. (VEN)",
  "Kouadio (MON)",
  "Troilo (PAR)",
  "Estupinan (MIL)",
  "Helland (BOL)",
  "Joao Mario (FIO)",
  "Palma (UDI)",
  "Lucchesi (MON)",
  "Halhal (VEN)",
  "Britschgi (PAR)",
  "Schingtienne (VEN)",
  "Drameh (GEN)",
  "Carboni A. (MON)",
  "Ranieri L. (FIO)",
  "Tchato (FRO)",
  "Franjic (VEN)",
  "Odenthal (SAS)",
  "Candè (SAS)",
  "Sverko (VEN)",
  "Kambwala (COM)",
  "Akpoguma (FRO)",
  "Ebosse (UDI)",
  "Casale (BOL)",
  "Idrissi R. (CAG)",
  "Van Der Brempt (SAS)",
  "Lulli (ROM)",
  "Abankwah (UDI)",
  "Ndiaye (PAR)",
  "Marin R. (NAP)",
  "Pellegrini Lu. (LAZ)",
  "Aurelio (CAG)",
  "Alhassane (BOL)",
  "Ndaba (LEC)",
  "Otoa (GEN)",
  "Goglichidze (MON)",
  "Lazzari (LAZ)",
  "Sabelli (GEN)",
  "Biraghi (TOR)",
  "Cinquegrano (SAS)",
  "Diawara S. (MIL)",
  "Bakoune (MON)",
  "Puczka (GEN)",
  "Jean (LEC)",
  "Sagrado (VEN)",
  "Terracciano F. (MIL)",
  "Drobnic (PAR)",
  "Mazzocchi (VEN)",
  "Ziolkowski (MON)",
  "Marianucci (NAP)",
  "Carboni F. (PAR)",
  "Cabal (JUV)",
  "De Silvestri (BOL)",
  "Rugani (JUV)",
  "Maye (MON)",
  "Omar Fayed (FRO)",
  "Gomes (VEN)",
  "Pieragnolo (SAS)",
  "Dembelè A. (LEC)",
  "Amey (FRO)",
  "Antov (MON)",
  "Goldaniga (COM)",
  "Patric (LAZ)",
  "Paz N. (COM)",
  "Calhanoglu (INT)",
  "McTominay (NAP)",
  "Orsolini (BOL)",
  "Pulisic (MIL)",
  "Rabiot (MIL)",
  "Baturina (COM)",
  "Mora (ROM)",
  "Da Cunha (COM)",
  "Barella (INT)",
  "Zaniolo (UDI)",
  "De Bruyne (NAP)",
  "McKennie (JUV)",
  "Zaccagni (LAZ)",
  "Atta (FIO)",
  "Vlasic (TOR)",
  "Conceicao (JUV)",
  "Taylor K. (LAZ)",
  "Samardzic (ATA)",
  "Ekkelenkamp (UDI)",
  "Goncalves P. (FIO)",
  "Jones C. (INT)",
  "Kessiè (ATA)",
  "Gonzalez N. (JUV)",
  "Modric (MIL)",
  "Zielinski (INT)",
  "Gudmundsson (LAZ)",
  "Mastantuono (FIO)",
  "Alajbegovic (JUV)",
  "Saelemaekers (MIL)",
  "Rodriguez Je. (COM)",
  "Baldanzi (GEN)",
  "Frattesi (LAZ)",
  "Konè M. (ROM)",
  "Zambo Anguissa (NAP)",
  "Rowe (ATA)",
  "Thorstvedt (SAS)",
  "Vergara (NAP)",
  "Perrone (COM)",
  "Bernardeschi (BOL)",
  "Diouf (INT)",
  "Politano (NAP)",
  "Locatelli (JUV)",
  "Cristante (ROM)",
  "Casadei (TOR)",
  "Volpato (SAS)",
  "Thuram K. (JUV)",
  "Cancellieri (LAZ)",
  "Isaksen (LAZ)",
  "Sucic P. (INT)",
  "Pellegrini Lo. (ROM)",
  "Colpani (MON)",
  "Mbangula (BOL)",
  "Calò (FRO)",
  "Hutchinson (MIL)",
  "Schmid (FRO)",
  "Cambiaghi (BOL)",
  "Chukwueze (MIL)",
  "Lobotka (NAP)",
  "Pasalic (ATA)",
  "Mandragora (TOR)",
  "Odgaard (BOL)",
  "Bernabè (PAR)",
  "Gaetano (ATA)",
  "Sarr P. (JUV)",
  "Ndour (FIO)",
  "Ferguson (BOL)",
  "Elmas (ATA)",
  "Romano (CAG)",
  "Karlstrom (UDI)",
  "Fagioli (FIO)",
  "Pisilli (ROM)",
  "Frendrup (GEN)",
  "Coulibaly L. (LEC)",
  "Zalewski (ATA)",
  "Unai Gomez (UDI)",
  "Sow (GEN)",
  "Koopmeiners (JUV)",
  "Rovella (LAZ)",
  "Adopo (CAG)",
  "Akinsanmiro (MON)",
  "Milla (COM)",
  "Fazzini (CAG)",
  "Braganca (TOR)",
  "Pierotti (LEC)",
  "Basic (VEN)",
  "Oulai (FIO)",
  "Zhegrova (JUV)",
  "Caqueret (COM)",
  "Piotrowski (UDI)",
  "Adzic (SAS)",
  "Ellertsson (GEN)",
  "Nicolussi Caviglia (PAR)",
  "Winks (CAG)",
  "Pessina (MON)",
  "Matic (SAS)",
  "Tourè I. (MON)",
  "Bakola (SAS)",
  "Oristanio (TOR)",
  "Zerbin (FRO)",
  "Pobega (BOL)",
  "Cissè A. (MIL)",
  "Fitz-Jim (TOR)",
  "Perez K. (VEN)",
  "Keita M. (PAR)",
  "Jashari (MIL)",
  "Dele-Bashiru (LAZ)",
  "Busio (VEN)",
  "Meichtry (GEN)",
  "Gineitis (TOR)",
  "Sohm (VEN)",
  "Luis Henrique (INT)",
  "Amondarain (BOL)",
  "Felici (CAG)",
  "Njie (FIO)",
  "Folorunsho (MON)",
  "Douglas Luiz (JUV)",
  "Loftus-Cheek (MIL)",
  "Fini (FRO)",
  "Moro N. (BOL)",
  "Massolin (CAG)",
  "Koutsoupias (FRO)",
  "Cichella (FRO)",
  "Amorim (GEN)",
  "Ngom (LEC)",
  "Miller L. (UDI)",
  "Dominguez B. (SAS)",
  "Almqvist (PAR)",
  "Berisha M. (LEC)",
  "Ricci S. (COM)",
  "Traorè Hj. (GEN)",
  "Cataldi (LAZ)",
  "Grillitsch (FRO)",
  "Gandelman (LEC)",
  "Addai (COM)",
  "Mkhitaryan (INT)",
  "De Roon (ROM)",
  "Fabbian (PAR)",
  "Ilkhan (TOR)",
  "Messias (GEN)",
  "Musah (MIL)",
  "Diallo O. (PAR)",
  "Gorter (LEC)",
  "Brescianini (FIO)",
  "Ordonez C. (PAR)",
  "Gilmour (NAP)",
  "Fernandez T. (VEN)",
  "Masini (FRO)",
  "Stankovic A. (INT)",
  "Sulemana I. (SAS)",
  "Maleh (LEC)",
  "Deiola (CAG)",
  "Gagliardini (CAG)",
  "Aboukhlal (TOR)",
  "Gelli F. (FRO)",
  "Colombo L. (MON)",
  "Helgason (VEN)",
  "Fadera (CAG)",
  "El Azzouzi O. (BOL)",
  "Jovanovic (UDI)",
  "Hasa (FRO)",
  "Lipani (SAS)",
  "Boloca (SAS)",
  "Ciurria (MON)",
  "Cremaschi (PAR)",
  "Venturino (GEN)",
  "Zarraga (UDI)",
  "Belahyane (LAZ)",
  "Duncan (VEN)",
  "Foe Ondoa (MON)",
  "Forson O. (MON)",
  "Mout (MON)",
  "Ilic (LEC)",
  "Anjorin (TOR)",
  "Kone B. (FRO)",
  "Comotto (MIL)",
  "Laerke (LEC)",
  "Dagasso (VEN)",
  "El Azzouzi A. (FRO)",
  "Lahdo (COM)",
  "Fofana Sa. (LEC)",
  "Liteta (CAG)",
  "Kaba (LEC)",
  "Ciervo (CAG)",
  "Malen (ROM)",
  "Martinez L. (INT)",
  "Hojlund (NAP)",
  "Thuram (INT)",
  "Ramos G. (MIL)",
  "Kolo Muani (JUV)",
  "Kean (COM)",
  "Woltemade (JUV)",
  "Douvikas (COM)",
  "Yildiz (JUV)",
  "Scamacca (ATA)",
  "Davis K. (UDI)",
  "Berardi (SAS)",
  "Krstovic (ATA)",
  "Esposito F.P. (INT)",
  "De Ketelaere (ATA)",
  "Dybala (ROM)",
  "Laurientè (SAS)",
  "Dovbyk (BOL)",
  "Simeone (TOR)",
  "Raspadori (ATA)",
  "Castro S. (ROM)",
  "Santos A. (NAP)",
  "Beto (FIO)",
  "Pellegrino M. (FIO)",
  "Soulè (ROM)",
  "Pinamonti (LAZ)",
  "Diao (COM)",
  "Esposito Se. (SAS)",
  "Kevin Carlos (CAG)",
  "Colombo (GEN)",
  "Adams A. (VEN)",
  "Romero D. (PAR)",
  "Tourè E. (PAR)",
  "Adams C. (TOR)",
  "Bowie (SAS)",
  "Bobcek (FRO)",
  "Yeboah J. (VEN)",
  "Raimondo (FRO)",
  "Cutrone (MON)",
  "Osmajic (GEN)",
  "Piccoli (BOL)",
  "Ghedjemis (FRO)",
  "Geubbels (LEC)",
  "Vitinha O. (GEN)",
  "Varela G. (MON)",
  "Boga (JUV)",
  "Gnonto (FIO)",
  "Bonny (INT)",
  "Rrahmani Al. (VEN)",
  "Kvernadze (FRO)",
  "Neres (NAP)",
  "Zeballos (MON)",
  "Stulic (LEC)",
  "Zapata D. (TOR)",
  "Mutandwa (CAG)",
  "Noslin (LAZ)",
  "Sulemana K. (ATA)",
  "Maldini (CAG)",
  "Ngonge (MON)",
  "Birligea (FRO)",
  "Camarda (MIL)",
  "Fatah (LEC)",
  "Lang (NAP)",
  "Mendy P. (CAG)",
  "N'Dri (LEC)",
  "Lucca (NAP)",
  "Kulenovic (TOR)",
  "Borrelli (CAG)",
  "Nzola (CAG)",
  "Milik (JUV)",
  "Gueye (UDI)",
  "Giovane (NAP)",
  "Mota (MON)",
  "Adorante (VEN)",
  "Robinson J. (MON)",
  "Havel (GEN)",
  "Frigan (PAR)",
  "Lontani (PAR)",
  "Elphege (PAR)",
  "Ekhator (JUV)",
  "Robinho Junior (GEN)",
  "Bayo V. (UDI)",
  "De Martis (PAR)",
  "Lauberbach (VEN)",
  "Lisman (VEN)",
  "Trepy (CAG)",
]
