export const centrocampisti: string[] = [
    "Paz N. (COM)",
    "Calhanoglu (INT)",
    "McTominay (NAP)",
    "Orsolini (BOL)",
    "Pulisic (MIL)",
    "Rabiot (MIL)",
    "Baturina (COM)",
    "Mora (ROM)",
    "Da Cunha (COM)",
    "Barella (INT)",
    "Zaniolo (UDI)",
    "De Bruyne (NAP)",
    "McKennie (JUV)",
    "Zaccagni (LAZ)",
    "Atta (FIO)",
    "Vlasic (TOR)",
    "Conceicao (JUV)",
    "Taylor K. (LAZ)",
    "Samardzic (ATA)",
    "Ekkelenkamp (UDI)",
    "Goncalves P. (FIO)",
    "Jones C. (INT)",
    "Kessiè (ATA)",
    "Gonzalez N. (JUV)",
    "Modric (MIL)",
    "Zielinski (INT)",
    "Gudmundsson (LAZ)",
    "Mastantuono (FIO)",
    "Alajbegovic (JUV)",
    "Saelemaekers (MIL)",
    "Rodriguez Je. (COM)",
    "Baldanzi (GEN)",
    "Frattesi (LAZ)",
    "Konè M. (ROM)",
    "Zambo Anguissa (NAP)",
    "Rowe (ATA)",
    "Thorstvedt (SAS)",
    "Vergara (NAP)",
    "Perrone (COM)",
    "Bernardeschi (BOL)",
    "Diouf (INT)",
    "Politano (NAP)",
    "Locatelli (JUV)",
    "Cristante (ROM)",
    "Casadei (TOR)",
    "Volpato (SAS)",
    "Thuram K. (JUV)",
    "Cancellieri (LAZ)",
    "Isaksen (LAZ)",
    "Sucic P. (INT)",
    "Pellegrini Lo. (ROM)",
    "Colpani (MON)",
    "Mbangula (BOL)",
    "Calò (FRO)",
    "Hutchinson (MIL)",
    "Schmid (FRO)",
    "Cambiaghi (BOL)",
    "El Shaarawy (GEN)",
    "Chukwueze (MIL)",
    "Lobotka (NAP)",
    "Pasalic (ATA)",
    "Mandragora (TOR)",
    "Odgaard (BOL)",
    "Bernabè (PAR)",
    "Gaetano (ATA)",
    "Sarr P. (JUV)",
    "Ndour (FIO)",
    "Ferguson (BOL)",
    "Elmas (ATA)",
    "Romano (CAG)",
    "Karlstrom (UDI)",
    "Fagioli (FIO)",
    "Pisilli (ROM)",
    "Frendrup (GEN)",
    "Coulibaly L. (LEC)",
    "Zalewski (ATA)",
    "Unai Gomez (UDI)",
    "Sow (GEN)",
    "Koopmeiners (JUV)",
    "Rovella (LAZ)",
    "Adopo (CAG)",
    "Akinsanmiro (MON)",
    "Milla (COM)",
    "Fazzini (CAG)",
    "Braganca (TOR)",
    "Pierotti (LEC)",
    "Basic (VEN)",
    "Oulai (FIO)",
    "Zhegrova (JUV)",
    "Caqueret (COM)",
    "Piotrowski (UDI)",
    "Adzic (SAS)",
    "Ellertsson (GEN)",
    "Nicolussi Caviglia (PAR)",
    "Winks (CAG)",
    "Pessina (MON)",
    "Matic (SAS)",
    "Tourè I. (MON)",
    "Bakola (SAS)",
    "Oristanio (TOR)",
    "Zerbin (FRO)",
    "Pobega (BOL)",
    "Cissè A. (MIL)",
    "Fitz-Jim (TOR)",
    "Perez K. (VEN)",
    "Keita M. (PAR)",
    "Jashari (MIL)",
    "Dele-Bashiru (LAZ)",
    "Busio (VEN)",
    "Meichtry (GEN)",
    "Gineitis (TOR)",
    "Sohm (VEN)",
    "Luis Henrique (INT)",
    "Amondarain (BOL)",
    "Felici (CAG)",
    "Njie (FIO)",
    "Folorunsho (MON)",
    "Douglas Luiz (JUV)",
    "Loftus-Cheek (MIL)",
    "Fini (FRO)",
    "Moro N. (BOL)",
    "Massolin (CAG)",
    "Koutsoupias (FRO)",
    "Cichella (FRO)",
    "Amorim (GEN)",
    "Ngom (LEC)",
    "Miller L. (UDI)",
    "Dominguez B. (SAS)",
    "Almqvist (PAR)",
    "Berisha M. (LEC)",
    "Ricci S. (COM)",
    "Traorè Hj. (GEN)",
    "Cataldi (LAZ)",
    "Grillitsch (FRO)",
    "Gandelman (LEC)",
    "Addai (COM)",
    "Mkhitaryan (INT)",
    "De Roon (ROM)",
    "Fabbian (PAR)",
    "Ilkhan (TOR)",
    "Messias (GEN)",
    "Musah (MIL)",
    "Diallo O. (PAR)",
    "Gorter (LEC)",
    "Brescianini (FIO)",
    "Ordonez C. (PAR)",
    "Gilmour (NAP)",
    "Fernandez T. (VEN)",
    "Masini (FRO)",
    "Stankovic A. (INT)",
    "Sulemana I. (SAS)",
    "Maleh (LEC)",
    "Deiola (CAG)",
    "Gagliardini (CAG)",
    "Aboukhlal (TOR)",
    "Gelli F. (FRO)",
    "Colombo L. (MON)",
    "Helgason (VEN)",
    "Fadera (CAG)",
    "El Azzouzi O. (BOL)",
    "Jovanovic (UDI)",
    "Hasa (FRO)",
    "Lipani (SAS)",
    "Boloca (SAS)",
    "Ciurria (MON)",
    "Cremaschi (PAR)",
    "Venturino (GEN)",
    "Zarraga (UDI)",
    "Belahyane (LAZ)",
    "Duncan (VEN)",
    "Foe Ondoa (MON)",
    "Forson O. (MON)",
    "Mout (MON)",
    "Ilic (LEC)",
    "Anjorin (TOR)",
    "Kone B. (FRO)",
    "Comotto (MIL)",
    "Laerke (LEC)",
    "Dagasso (VEN)",
    "El Azzouzi A. (FRO)",
    "Lahdo (COM)",
    "Fofana Sa. (LEC)",
    "Liteta (CAG)",
    "Kaba (LEC)",
    "Ciervo (CAG)"
]