export const difensori: string[] = [
    "Dimarco (INT)",
    "Wesley (ROM)",
    "Molina N. (ROM)",
    "Mancini (ROM)",
    "Rrahmani (NAP)",
    "Akanji (INT)",
    "Pavlovic (MIL)",
    "Kalulu (JUV)",
    "Bastoni (INT)",
    "Solet (UDI)",
    "N'Dicka (ROM)",
    "Gila (MIL)",
    "Di Lorenzo (NAP)",
    "Bisseck (INT)",
    "Stones (INT)",
    "Ostigard (GEN)",
    "Spence (INT)",
    "Hermoso (ROM)",
    "Chalobah T. (COM)",
    "Ramon (COM)",
    "Scalvini (ATA)",
    "Vasquez (GEN)",
    "Dodò (FIO)",
    "Vojvoda (UDI)",
    "Kamara H. (UDI)",
    "Couto (COM)",
    "Spinazzola (NAP)",
    "Bartesaghi (MIL)",
    "Valeri (PAR)",
    "Miranda J. (BOL)",
    "Tiago Gabriel (LEC)",
    "Delprato (PAR)",
    "Theate (BOL)",
    "Zappacosta (ATA)",
    "Cambiaso (JUV)",
    "Koulierakis (ROM)",
    "Doekhi (LAZ)",
    "Celik (JUV)",
    "Comuzzo (TOR)",
    "Tavares N. (LAZ)",
    "Belghali (TOR)",
    "Dragusin (FIO)",
    "Mina (CAG)",
    "Sutalo J. (LAZ)",
    "Idzes (SAS)",
    "Zortea (BOL)",
    "Jimenez A. (FIO)",
    "Lucumì (JUV)",
    "Badiashile (NAP)",
    "Mangas (MON)",
    "Bracaglia (FRO)",
    "Obert (CAG)",
    "Gabbia (MIL)",
    "Coco (TOR)",
    "Ismajli (TOR)",
    "Hien (ATA)",
    "Valle (COM)",
    "Kristensen T. (ATA)",
    "Carlos Augusto (INT)",
    "Marusic (LAZ)",
    "Bernasconi (ATA)",
    "Bellanova (ATA)",
    "Sugawara (CAG)",
    "Heggem (BOL)",
    "Caleta-Car (SAS)",
    "Buongiorno (NAP)",
    "Kaiki (COM)",
    "Obrador (SAS)",
    "Marcandalli (GEN)",
    "Holm (BOL)",
    "Monterisi (FRO)",
    "Pedraza (LAZ)",
    "Pavard (INT)",
    "Leysen F. (SAS)",
    "Viery (FIO)",
    "Fortini (TOR)",
    "Veiga D. (LEC)",
    "Beukema (NAP)",
    "Balerdi (ROM)",
    "Gallo (LEC)",
    "Oyono A. (FRO)",
    "Tomori (MIL)",
    "Kolasinac (ATA)",
    "De Winter (MIL)",
    "Valdepenas (FIO)",
    "Calvani (FRO)",
    "Zè Pedro (CAG)",
    "Bella-Kotchap (VEN)",
    "Kempf (COM)",
    "Olivera (NAP)",
    "Kelly L. (JUV)",
    "Gaspar K. (LEC)",
    "Patterson (TOR)",
    "Correia T. (VEN)",
    "Ghilardi (ROM)",
    "Doig (SAS)",
    "Haps (VEN)",
    "Kofler (CAG)",
    "Rodriguez Ju. (CAG)",
    "Provstgaard (LAZ)",
    "Rensch (ROM)",
    "Favasuli (NAP)",
    "Comert (TOR)",
    "Siebert (LEC)",
    "Hainaut (VEN)",
    "Birindelli (MON)",
    "Kossounou (ATA)",
    "Kabasele (UDI)",
    "Mitaj (GEN)",
    "Mussolini (LAZ)",
    "Vitik (BOL)",
    "Smolcic I. (COM)",
    "Gatti (JUV)",
    "Bertola (UDI)",
    "Zanoli (UDI)",
    "Parisi (FIO)",
    "Valenti (PAR)",
    "Walukiewicz (SAS)",
    "Juan Jesus (VEN)",
    "Arizala (UDI)",
    "Cittadini (FRO)",
    "Pongracic (FIO)",
    "Terzic (FRO)",
    "Moreno M. (VEN)",
    "Kouadio (MON)",
    "Troilo (PAR)",
    "Estupinan (MIL)",
    "Helland (BOL)",
    "Joao Mario (FIO)",
    "Palma (UDI)",
    "Lucchesi (MON)",
    "Halhal (VEN)",
    "Britschgi (PAR)",
    "Schingtienne (VEN)",
    "Drameh (GEN)",
    "Carboni A. (MON)",
    "Ranieri L. (FIO)",
    "Tchato (FRO)",
    "Franjic (VEN)",
    "Odenthal (SAS)",
    "Candè (SAS)",
    "Sverko (VEN)",
    "Kambwala (COM)",
    "Akpoguma (FRO)",
    "Ebosse (UDI)",
    "Casale (BOL)",
    "Idrissi R. (CAG)",
    "Van Der Brempt (SAS)",
    "Lulli (ROM)",
    "Abankwah (UDI)",
    "Ndiaye (PAR)",
    "Marin R. (NAP)",
    "Pellegrini Lu. (LAZ)",
    "Aurelio (CAG)",
    "Alhassane (BOL)",
    "Ndaba (LEC)",
    "Otoa (GEN)",
    "Goglichidze (MON)",
    "Lazzari (LAZ)",
    "Sabelli (GEN)",
    "Biraghi (TOR)",
    "Cinquegrano (SAS)",
    "Diawara S. (MIL)",
    "Bakoune (MON)",
    "Puczka (GEN)",
    "Jean (LEC)",
    "Sagrado (VEN)",
    "Terracciano F. (MIL)",
    "Drobnic (PAR)",
    "Mazzocchi (VEN)",
    "Ziolkowski (MON)",
    "Marianucci (NAP)",
    "Carboni F. (PAR)",
    "Cabal (JUV)",
    "De Silvestri (BOL)",
    "Rugani (JUV)",
    "Maye (MON)",
    "Omar Fayed (FRO)",
    "Gomes (VEN)",
    "Pieragnolo (SAS)",
    "Dembelè A. (LEC)",
    "Amey (FRO)",
    "Antov (MON)",
    "Goldaniga (COM)",
    "Patric (LAZ)"
]