const portieri: string[] = [
    "Svilar (ROM)",
    "Vicario (JUV)",
    "Martinez Jo. (INT)",
    "Carnesecchi (ATA)",
    "Maignan (MIL)",
    "Butez (COM)",
    "Meret (NAP)",
    "Mandas (LAZ)",
    "Skorupski (BOL)",
    "De Gea (FIO)",
    "Okoye (UDI)",
    "Perri (TOR)",
    "Falcone (LEC)",
    "Sanchez Ro. (COM)",
    "Caprile (CAG)",
    "Bijlow (GEN)",
    "Muric (SAS)",
    "Palmisani (FRO)",
    "Stankovic F. (VEN)",
    "Tornqvist (MON)",
    "Corvi (PAR)",
    "Daffara (PAR)",
    "Mascardi (TOR)",
    "Thiam (MON)",
    "Provedel (INT)",
    "Milinkovic-Savic V. (NAP)",
    "Pompei (ATA)",
    "Mrozek (UDI)",
    "Grabara (JUV)",
    "Pisseri (FRO)",
    "Penev (LEC)",
    "Renzetti (LAZ)",
    "Happonen (BOL)",
    "Pozzi (VEN)",
    "Strajnar (MON)",
    "Lolic (FRO)",
    "Desplanches (FRO)",
    "Siviero (TOR)",
    "Motta (LAZ)",
    "Pessina Mas. (BOL)",
    "De Marzi (ROM)",
    "Torriani (MIL)",
    "Grandi (VEN)",
    "Sherri (CAG)",
    "Stolz (GEN)",
    "Christensen O. (FIO)",
    "Piana (UDI)",
    "Paleari (TOR)",
    "Montipò (VEN)",
    "Turati (SAS)",
    "Russo A. (SAS)",
    "Bleve (LEC)",
    "Ghidotti (PAR)",
    "Contini (NAP)",
    "Terracciano (MIL)",
    "Vigorito (COM)",
    "Satalino (SAS)",
    "Pinsoglio (JUV)",
    "Di Gennaro (INT)",
    "Gollini (ROM)",
    "Padelli (UDI)",
    "Sommariva (GEN)",
    "Lezzerini (FIO)",
    "Sportiello (ATA)",
    "Radunovic (CAG)"
];